name: Flutter SonarCloud Analysis

on:
  push:
    branches:
      - fix_sonar_cloud

jobs:
  analyze:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # or your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Install Sonar Dart Plugin
        run: flutter pub global activate sonar

      - name: Run SonarCloud Scanner
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN }}
        run: flutter pub global run sonar
