name: "Build & Release"

on:
  push:
    branches: [ "fix_sonar_cloud" ]
  pull_request:
    branches: [ "fix_sonar_cloud" ]

permissions:
  contents: write  # ✅ Needed to allow creating releases

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./voice_bridge

      - name: Build APK (Release & Split per ABI)
        run: flutter build apk --release --split-per-abi
        working-directory: ./voice_bridge

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "voice_bridge/build/app/outputs/apk/release/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
