name: Flutter SonarCloud Analysis

on:
  push:
    branches: [ "fix_sonar_cloud" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./voice_bridge

      - name: Run tests with coverage
        run: flutter test --coverage
        working-directory: ./voice_bridge

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_ode-to-code
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.java.version=17
            -Dsonar.verbose=true
            -Dsonar.javascript.lcov.reportPaths=voice_bridge/coverage/lcov.info
            -Dsonar.sources=voice_bridge/lib
            -Dsonar.tests=voice_bridge/test
            -Dsonar.test.inclusions=voice_bridge/test/features/**/*_test.dart
            -Dsonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,**/__generated__/**,**/mocks.dart,**/*.css,voice_bridge/lib/core/localization/**/*app_translations.dart
